# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3254533fe322b5bc397f6840002e1879018fc2fccd691fb229a7b8fe45a43a54972876047eb396e0d7f71bb412f2669ee5bd9fc48ca8f489656a5199affdf350

test:
  secret_key_base: 4fdd8e213227aeb61609f93abc15acc4c2dd883637e879b7cbcd5a14d86499a90e800c0690a98afd1d96c83a908fb0180dd15ca2023313a6feff18398d810527

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
